export const USER_INPUT_REQUEST = "USER_INPUT_REQUEST";
export const USER_INPUT_SUCCESS = "USER_INPUT_SUCCESS";
export const USER_INPUT_FAIL = "USER_INPUT_FAIL";


export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";